name: ðŸš€ ì¡°ì§ ë ˆí¬ > fork ë ˆí¬ (Vercel ë°°í¬)
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Create and copy files
        run: |
          mkdir -p output
          cp -R ./* ./.[^.]* output/ 2>/dev/null || :
          rm -rf output/output
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: fecapark
          destination-repository-name: slack-archive-client
          user-email: ${{ secrets.USER_EMAIL }}
          user-name: fecapark
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
